# Generated by Django 5.2.17 on 2026-10-02 23:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='circle', max_length=40)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], default='slate', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlannerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='layout-template', max_length=40)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], default='indigo', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlannerTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(blank=True, choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planner.activitycategory')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='challenges.challenge')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.plannertemplate')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(blank=True, choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Selected days'), ('interval', 'Every N days')], default='weekly', max_length=10)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='0 = Monday … 6 = Sunday')),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='planner.activitycategory')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(blank=True, choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='planned', max_length=12)),
                ('occurrence_date', models.DateField(blank=True, null=True)),
                ('is_detached', models.BooleanField(default=False, help_text='Edited individually; no longer follows its rule.')),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='planner.activitycategory')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_activities', to='challenges.challenge')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='planner.plannedactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_activities', to=settings.AUTH_USER_MODEL)),
                ('recurring_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='planner.recurringrule')),
            ],
            options={
                'verbose_name_plural': 'planned activities',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitycategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_activity_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='plannertemplate',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_planner_template_per_user'),
        ),
        migrations.AddConstraint(
            model_name='plannertemplateitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time', datetime.time(0, 0)), _connector='OR'), name='template_item_time_range'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['user', 'is_active'], name='planner_rec_user_id_136337_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time', datetime.time(0, 0)), _connector='OR'), name='rule_time_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 1)), name='rule_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='rule_date_range'),
        ),
        migrations.AddIndex(
            model_name='plannedactivity',
            index=models.Index(fields=['user', 'date'], name='planner_pla_user_id_a0a34d_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedactivity',
            index=models.Index(fields=['user', 'status'], name='planner_pla_user_id_dcc6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedactivity',
            index=models.Index(fields=['challenge', 'date'], name='planner_pla_challen_84fa21_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedactivity',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time', datetime.time(0, 0)), _connector='OR'), name='activity_time_range'),
        ),
        migrations.AddConstraint(
            model_name='plannedactivity',
            constraint=models.UniqueConstraint(fields=('recurring_rule', 'occurrence_date'), name='uniq_rule_occurrence'),
        ),
    ]
