# Generated by Django 5.2.17 on 2026-10-04 21:29

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_goal_metric_restrict'),
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedactivity',
            name='activity_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='plannertemplateitem',
            name='template_item_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='recurringrule',
            name='rule_time_range',
        ),
        migrations.AddConstraint(
            model_name='plannedactivity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time', models.F('start_time')), _negated=True), ('start_time', datetime.time(0, 0)), _connector='OR'), name='activity_time_range_v2'),
        ),
        migrations.AddConstraint(
            model_name='plannertemplateitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time', models.F('start_time')), _negated=True), ('start_time', datetime.time(0, 0)), _connector='OR'), name='template_item_time_range_v2'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time', models.F('start_time')), _negated=True), ('start_time', datetime.time(0, 0)), _connector='OR'), name='rule_time_range_v2'),
        ),
    ]
