# Generated by Django 5.2.17 on 2026-10-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='morning_summary_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Send to devices where push is enabled.'),
        ),
    ]
