# Generated by Django 5.2.17 on 2026-10-04 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersetting_morning_summary_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='end_of_day_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='morning_summary_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
