# Generated by Django 5.2.17 on 2026-10-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_time_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('ar', 'العربية')], default='en', max_length=8),
        ),
    ]
