# Generated by Django 5.2.17 on 2026-10-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_arabic_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calendar_token',
            field=models.CharField(blank=True, editable=False, max_length=48, null=True, unique=True),
        ),
    ]
