# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('challenge_created', 'Challenge created'), ('challenge_updated', 'Challenge updated'), ('challenge_status', 'Challenge status changed'), ('challenge_deleted', 'Challenge deleted'), ('goal_changed', 'Goal changed'), ('schedule_changed', 'Schedule changed'), ('entry_created', 'Entry created'), ('entry_updated', 'Entry modified'), ('entry_deleted', 'Entry deleted'), ('activity_created', 'Planner activity created'), ('activity_updated', 'Planner activity modified'), ('activity_status', 'Planner activity status changed'), ('activity_deleted', 'Planner activity deleted'), ('rule_changed', 'Recurring rule changed'), ('template_applied', 'Day template applied'), ('report_generated', 'Report generated'), ('account', 'Account event')], max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx')],
            },
        ),
    ]
