# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('challenge', 'Challenge')], default='day', max_length=10)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('content', models.TextField(max_length=20000)),
                ('mood', models.PositiveSmallIntegerField(blank=True, choices=[(1, '😞'), (2, '😕'), (3, '😐'), (4, '🙂'), (5, '😄')], null=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='journal_jou_user_id_601e4b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mood__isnull', True), models.Q(('mood__gte', 1), ('mood__lte', 5)), _connector='OR'), name='journal_mood_range')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('went_well', models.TextField(blank=True, max_length=5000)),
                ('difficult', models.TextField(blank=True, max_length=5000)),
                ('improve', models.TextField(blank=True, max_length=5000)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_weekly_review'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='weekly_review_rating_range')],
            },
        ),
    ]
