#!/usr/bin/env bash
# LifeFlow on PythonAnywhere (free "Beginner" account, no credit card).
#
# In a PythonAnywhere *Bash console*:
#   git clone https://github.com/<github-user>/lifeflow.git ~/lifeflow
#   bash ~/lifeflow/deploy/pythonanywhere.sh            # first installation
#   bash ~/lifeflow/deploy/pythonanywhere.sh update     # later: pull the new version and reload
#
# EU accounts (eu.pythonanywhere.com): prefix with  PA_DOMAIN=$USER.eu.pythonanywhere.com
# Database: SQLite file in ~/lifeflow-data (outside the code folder, so updates never touch it).
set -euo pipefail

APP_DIR="$HOME/lifeflow"
DATA_DIR="$HOME/lifeflow-data"
VENV="$HOME/.virtualenvs/lifeflow"
DOMAIN="${PA_DOMAIN:-$USER.pythonanywhere.com}"
WSGI_FILE="/var/www/${DOMAIN//./_}_wsgi.py"
export DJANGO_SETTINGS_MODULE=config.settings.prod

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
cd "$APP_DIR"

install_requirements() {
  # mysqlclient (MySQL), gunicorn/waitress (other servers) are not needed here.
  grep -viE '^(mysqlclient|gunicorn|waitress)' requirements.txt > /tmp/lifeflow-requirements.txt
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet -r /tmp/lifeflow-requirements.txt
}

django() { "$VENV/bin/python" manage.py "$@"; }

if [ "${1:-}" = "update" ]; then
  say "Updating LifeFlow"
  git pull --ff-only
  install_requirements
  django migrate --noinput
  django collectstatic --noinput -v 0
  touch "$WSGI_FILE"   # reloads the web app
  say "Done — https://$DOMAIN is running the new version."
  exit 0
fi

say "1/6 Python virtual environment"
PY=""
for candidate in python3.13 python3.12 python3.11; do
  if command -v "$candidate" >/dev/null 2>&1; then PY="$candidate"; break; fi
done
[ -n "$PY" ] || { echo "Python 3.11+ not found"; exit 1; }
[ -d "$VENV" ] || "$PY" -m venv "$VENV"
install_requirements

say "2/6 Configuration (.env)"
mkdir -p "$DATA_DIR"
if [ ! -f .env ]; then
  rand() { "$VENV/bin/python" -c "import secrets; print(secrets.token_urlsafe($1))"; }
  cat > .env <<EOF
# Generated by deploy/pythonanywhere.sh — never commit this file.
SECRET_KEY=$(rand 50)
DEBUG=False
ALLOWED_HOSTS=$DOMAIN
CSRF_TRUSTED_ORIGINS=https://$DOMAIN
SITE_URL=https://$DOMAIN
DB_ENGINE=sqlite
SQLITE_PATH=$DATA_DIR/lifeflow.sqlite3
USE_HTTPS=True
# HTTPS redirect is done by PythonAnywhere ("Force HTTPS" in the Web tab).
SECURE_SSL_REDIRECT=False
DEFAULT_TIMEZONE=Africa/Casablanca
CRON_TOKEN=$(rand 32)
EOF
  echo "Created .env"
else
  echo ".env already exists — kept as is"
fi

say "3/6 Database and static files"
django migrate --noinput
django collectstatic --noinput -v 0
grep -q '^VAPID_PRIVATE_KEY=.\+' .env || django generate_vapid_keys --write

say "4/6 Web app entry point ($WSGI_FILE)"
if [ ! -f "$WSGI_FILE" ]; then
  echo "Create the web app first: Web tab → Add a new web app → Manual configuration → Python 3.x,"
  echo "then run this script again."
  exit 1
fi
cp "$WSGI_FILE" "$WSGI_FILE.bak" 2>/dev/null || true
cat > "$WSGI_FILE" <<EOF
# LifeFlow — written by deploy/pythonanywhere.sh
import os
import sys

path = "$APP_DIR"
if path not in sys.path:
    sys.path.insert(0, path)
os.environ["DJANGO_SETTINGS_MODULE"] = "config.settings.prod"

from django.core.wsgi import get_wsgi_application  # noqa: E402

application = get_wsgi_application()
EOF

say "5/6 Administrator account"
if django shell -c "from django.contrib.auth import get_user_model as g; import sys; sys.exit(0 if g().objects.filter(is_superuser=True).exists() else 1)"; then
  echo "An administrator already exists."
elif [ -n "${DJANGO_SUPERUSER_PASSWORD:-}" ]; then
  django createsuperuser --noinput   # uses DJANGO_SUPERUSER_USERNAME / _EMAIL / _PASSWORD
else
  django createsuperuser
fi

say "6/6 Check"
django doctor || true

CRON_TOKEN_VALUE=$(grep '^CRON_TOKEN=' .env | cut -d= -f2-)
cat <<EOF

LifeFlow is installed. Last steps in the PythonAnywhere *Web* tab:
  • Virtualenv:  $VENV
  • Security:    turn ON "Force HTTPS"
  • Click the green "Reload $DOMAIN" button, then open https://$DOMAIN

Reminders (free external cron, e.g. cron-job.org), every 10 minutes:
  URL:     https://$DOMAIN/internal/cron/reminders/
  Header:  X-Cron-Token: $CRON_TOKEN_VALUE

Free web apps expire after one month: in the Web tab, click "Run until 1 month from today" when reminded.
EOF
