# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='tag', max_length=40)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], default='slate', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'challenge categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('icon', models.CharField(default='target', max_length=40)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], default='indigo', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for an open-ended challenge.', null=True)),
                ('closed_on', models.DateField(blank=True, help_text='Date the challenge was completed/archived early.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.challengecategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengePause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='challenges.challenge')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='target', max_length=40)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], default='indigo', max_length=20)),
                ('category_name', models.CharField(blank=True, max_length=60)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('definition', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.challengetemplate'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='challenges.challenge')),
            ],
            options={
                'ordering': ['target_value'],
            },
        ),
        migrations.CreateModel(
            name='RestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=140)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rest_days', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('weekdays', 'Selected days of the week'), ('interval', 'Every N days')], default='daily', max_length=10)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='0 = Monday … 6 = Sunday')),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='challenges.challenge')),
            ],
            options={
                'ordering': ['effective_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrackingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=60)),
                ('field_type', models.CharField(choices=[('boolean', 'Done / Not done'), ('integer', 'Whole number'), ('decimal', 'Decimal number'), ('duration', 'Duration (minutes)'), ('time', 'Time of day'), ('text', 'Text'), ('select', 'Choice list')], max_length=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choices for select fields.')),
                ('required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive fields keep their history but are hidden from forms.')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='challenges.challenge')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('period', models.CharField(choices=[('daily', 'per day'), ('weekly', 'per week'), ('monthly', 'per month'), ('total', 'in total')], default='daily', max_length=10)),
                ('aggregation', models.CharField(choices=[('sum', 'Sum of the measured value'), ('count', 'Number of qualifying entries')], default='sum', max_length=8)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_per_entry', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value for an entry to count (e.g. at least 30 minutes).', max_digits=12, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='challenges.challenge')),
                ('metric', models.ForeignKey(blank=True, help_text='Field that is measured. Empty = count entries (sessions).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='challenges.trackingfield')),
            ],
            options={
                'ordering': ['effective_from', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='challengecategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_challenge_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='challengepause',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='pause_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='challengetemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_template_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['user', 'status'], name='challenges__user_id_441a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['user', 'start_date'], name='challenges__user_id_b1c9e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='challenge_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='milestone_target_positive'),
        ),
        migrations.AddIndex(
            model_name='restday',
            index=models.Index(fields=['user', 'date'], name='challenges__user_id_abd0da_idx'),
        ),
        migrations.AddConstraint(
            model_name='restday',
            constraint=models.UniqueConstraint(fields=('user', 'challenge', 'date'), name='uniq_rest_day'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['challenge', 'effective_from'], name='challenges__challen_f6fe48_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 1)), name='schedule_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='schedule_effective_range'),
        ),
        migrations.AddConstraint(
            model_name='trackingfield',
            constraint=models.UniqueConstraint(fields=('challenge', 'key'), name='uniq_field_key_per_challenge'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['challenge', 'effective_from'], name='challenges__challen_4d2fd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('target__gt', 0)), name='goal_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='goal_effective_range'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('min_per_entry__isnull', True), ('min_per_entry__gte', 0), _connector='OR'), name='goal_min_per_entry_positive'),
        ),
    ]
