# Generated by Django 5.2.17 on 2026-10-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_system_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='metric',
            field=models.ForeignKey(blank=True, help_text='Field that is measured. Empty = count entries (sessions).', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='challenges.trackingfield'),
        ),
    ]
