# Generated by Django 5.2.17 on 2026-10-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_goal_metric_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Daily reminder on active days, if not done yet.', null=True),
        ),
    ]
