# Generated by Django 5.2.17 on 2026-10-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='time_comparison',
            field=models.CharField(blank=True, choices=[('before', 'before'), ('after', 'after')], max_length=6),
        ),
        migrations.AddField(
            model_name='goal',
            name='time_threshold',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
