# Generated by Django 5.2.17 on 2026-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_sync_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='direction',
            field=models.CharField(choices=[('at_least', 'at least'), ('at_most', 'at most')], default='at_least', max_length=8),
        ),
    ]
