/* LifeFlow service worker — generated by Django (apps/core/pwa.py). Version {{ version }}. */
"use strict";
const VERSION = "{{ version }}";
const SHELL_CACHE = `lf-shell-${VERSION}`;
const PAGE_CACHE = "lf-pages";
const API_CACHE = "lf-api";
const OFFLINE_URL = "{{ offline_url }}";
const SHELL = [OFFLINE_URL{% for url in shell %}, "{{ url|escapejs }}"{% endfor %}];
const MAX_PAGES = 30;
// API reads kept for offline use (personal data: cleared on logout).
const API_CACHEABLE = [/^\/api\/planner\/today\//, /^\/api\/planner\/(\?|$)/, /^\/api\/planner\/week\//, /^\/api\/challenges\/\?/,
  /^\/api\/planner\/categories\//, /^\/api\/dashboard\//, /^\/api\/notifications\//];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(SHELL_CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("lf-shell-") && k !== SHELL_CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "clear-user-data") {
    event.waitUntil(Promise.all([caches.delete(PAGE_CACHE), caches.delete(API_CACHE)]));
  }
});

async function trimCache(name, max) {
  const cache = await caches.open(name);
  const keys = await cache.keys();
  for (let i = 0; i < keys.length - max; i++) await cache.delete(keys[i]);
}

async function networkFirst(request, cacheName, fallbackUrl) {
  try {
    const response = await fetch(request);
    if (response.ok && response.type === "basic" && !response.redirected) {
      const cache = await caches.open(cacheName);
      cache.put(request, response.clone());
      if (cacheName === PAGE_CACHE) trimCache(PAGE_CACHE, MAX_PAGES);
    }
    return response;
  } catch (err) {
    const cached = await caches.match(request, { ignoreVary: true });
    if (cached) return cached;
    if (fallbackUrl) return caches.match(fallbackUrl);
    return new Response(JSON.stringify({ detail: "offline", offline: true }), { status: 503, headers: { "Content-Type": "application/json" } });
  }
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(SHELL_CACHE);
  const cached = await cache.match(request);
  const network = fetch(request).then((response) => {
    if (response.ok) cache.put(request, response.clone());
    return response;
  }).catch(() => cached);
  return cached || network;
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith("/admin/") || url.pathname.startsWith("/accounts/") || url.pathname.endsWith("/pdf/") || url.pathname.startsWith("/reports/export") || url.pathname.endsWith(".ics")) return;

  if (url.pathname.startsWith("/static/")) {
    event.respondWith(staleWhileRevalidate(request));
  } else if (url.pathname.startsWith("/api/")) {
    if (API_CACHEABLE.some((re) => re.test(url.pathname + url.search))) event.respondWith(networkFirst(request, API_CACHE));
  } else if (request.mode === "navigate") {
    event.respondWith(networkFirst(request, PAGE_CACHE, OFFLINE_URL));
  }
});

/* ---------------------------------------------------------------- Web Push */
self.addEventListener("push", (event) => {
  let data = {};
  try { data = event.data ? event.data.json() : {}; } catch (e) { data = { title: event.data && event.data.text() }; }
  const title = data.title || "LifeFlow";
  event.waitUntil(self.registration.showNotification(title, {
    body: data.body || "",
    icon: "{{ icon|escapejs }}",
    badge: "{{ icon|escapejs }}",
    tag: data.tag || undefined,
    data: { url: data.url || "/today/" },
  }));
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const target = new URL((event.notification.data && event.notification.data.url) || "/", self.location.origin).href;
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((wins) => {
      const existing = wins.find((w) => w.url.startsWith(self.location.origin));
      if (existing) { existing.navigate(target); return existing.focus(); }
      return self.clients.openWindow(target);
    })
  );
});
