# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('planner', 'From planner'), ('quick_add', 'Quick add')], default='manual', max_length=12)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='challenges.challenge')),
                ('planned_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='planner.plannedactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'challenge entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_time', models.TimeField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tracking.challengeentry')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='challenges.trackingfield')),
            ],
        ),
        migrations.AddIndex(
            model_name='challengeentry',
            index=models.Index(fields=['challenge', 'date'], name='tracking_ch_challen_375700_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeentry',
            index=models.Index(fields=['user', 'date'], name='tracking_ch_user_id_7f2552_idx'),
        ),
        migrations.AddIndex(
            model_name='entryfieldvalue',
            index=models.Index(fields=['field', 'entry'], name='tracking_en_field_i_cc5194_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryfieldvalue',
            constraint=models.UniqueConstraint(fields=('entry', 'field'), name='uniq_value_per_entry_field'),
        ),
    ]
