# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField()),
                ('user_display_name', models.CharField(max_length=150)),
                ('timezone', models.CharField(max_length=64)),
                ('summary', models.JSONField(default=dict)),
                ('planner', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReportChallengeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('goal_description', models.CharField(max_length=160)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('is_duration', models.BooleanField(default=False)),
                ('goal', models.FloatField(default=0)),
                ('actual', models.FloatField(default=0)),
                ('expected', models.FloatField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('gap', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('completion_rate', models.FloatField(blank=True, null=True)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('streak_unit', models.CharField(blank=True, max_length=10)),
                ('average', models.FloatField(blank=True, null=True)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('completed_periods', models.PositiveIntegerField(default=0)),
                ('due_periods', models.PositiveIntegerField(default=0)),
                ('daily_series', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='challenges.challenge')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='reports.monthlyreport')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['user', 'year', 'month'], name='reports_mon_user_id_357cd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month', 'version'), name='uniq_report_version'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='report_month_range'),
        ),
    ]
