# Generated by Django 5.2.17 on 2026-10-05 19:40

import apps.social.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0008_sync_templates_v3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('icon', models.CharField(default='target', max_length=40)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('sky', 'Sky'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('lime', 'Lime'), ('amber', 'Amber'), ('orange', 'Orange'), ('rose', 'Rose'), ('pink', 'Pink'), ('violet', 'Violet')], default='indigo', max_length=20)),
                ('definition', models.JSONField(default=dict, help_text='Wizard payload: fields, goal, schedule.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('invite_code', models.CharField(default=apps.social.models.new_invite_code, max_length=24, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shared_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['to_user', 'status'], name='social_frie_to_user_084357_idx'), models.Index(fields=['from_user', 'status'], name='social_frie_from_us_353929_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='uniq_friend_request'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='no_self_friendship')],
            },
        ),
        migrations.CreateModel(
            name='SharedChallengeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Member'), ('left', 'Left')], default='invited', max_length=10)),
                ('share_progress', models.BooleanField(default=True, help_text='Show my progress in the group leaderboard.')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(blank=True, help_text="The member's personal copy (private entries).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_memberships', to='challenges.challenge')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.sharedchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='social_shar_user_id_186947_idx')],
                'constraints': [models.UniqueConstraint(fields=('shared', 'user'), name='uniq_shared_member')],
            },
        ),
    ]
