# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('activity_reminder', 'Activity reminder'), ('challenge_reminder', 'Challenge reminder'), ('daily_goal', 'Daily goal'), ('end_of_day', 'End of day'), ('weekly_review', 'Weekly review'), ('report_ready', 'Report ready'), ('milestone', 'Milestone reached'), ('system', 'System')], default='system', max_length=24)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, help_text='Prevents sending the same reminder twice.', max_length=120, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dedupe_key'), name='uniq_notification_dedupe')],
            },
        ),
    ]
